apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
        - name: netflix-app
          image: 211125610248.dkr.ecr.us-east-1.amazonaws.com/netflix-clone:master-7a5f34f043c6f5402147dffd064454dffce9f572
          ports:
            - containerPort: 80
