apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
        - name: netflix-app
          image: 767398067552.dkr.ecr.ap-south-1.amazonaws.com/neflix-project:master-bae8bb77c753c1aab05c53f308c480a3522b0bcf
          ports:
            - containerPort: 80
